apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
    name: template-data
    description: Approved templates for Backstage for AWS
spec:
    targets: 
      - ./example-nodejs-eks/template.yaml
      - ./create-ec2-terraform/template.yaml
      - ./create-github-repository/template.yaml
    rules:
        - allow: [Template]
