apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-vpc-crossplane
  title: Creates a Amazon VPC by Crossplane
  description: Creates a Amazon VPC by Crossplane
  tags: ['crossplane', 'aws', 'vpc', 'network']
spec:
  owner: guest
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: User
    - title: Configuration VPC options
      properties:
        vpcCidrBlock:
          title: VpcCidrBlock
          type: string
          description: Network CIDR block of the Amazon VPC
          ui:autofocus: true
    - title: Configuration repository options
      properties:
        repoUrl: # need a place to store this entity information.
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            # allowedOwners: ['shazi7804']
            allowedHosts: ['github.com']
        formBranch:
          type: string
        targetBranchName:
          default: main
          type: string
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        targetPath: ./templates/backstage/create-vpc-crossplane
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          vpcCidr: ${{ parameters.vpcCidrBlock }}
    - id: pull-request
      name: Publishing Pull Request to Github
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: ${{ parameters.formBranch }}
        targetBranchName: ${{ parameters.targetBranchName }}
        title: Create an Amazon VPC
        description: Create an Amazon VPC with CIDR block ${{ parameters.vpcCidrBlock }}
        commitMessage: Create an Amazon VPC with CIDR block ${{ parameters.vpcCidrBlock }} by ${{ parameters.owner }}
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: ${{ user.entity.spec.profile.email }}
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
